volumes:
  ollama_vol:
    driver: local
  anythingllm_vol:
    driver: local

networks:
  panic:
    driver: bridge

services:

  ollama:
    image: ollama/ollama:latest
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: volume
        source: ollama_vol
        target: /root/.ollama
        volume:
          nocopy: true
    container_name: ollama
    restart: no
    ports:
      - "127.0.0.1:11434:11434"
    networks:
      - panic
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-I",
          "http://localhost:11434 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  archive:
    depends_on:
      ollama:
        condition: service_started
    container_name: LOADERBOT
    image: mintplexlabs/anythingllm:latest
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./archive:/app/server/storage
      - ./.env:/app/server/.env
      - ./collector/hotdir/:/app/collector/hotdir
      - ./collector/outputs/:/app/collector/outputs
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - STORAGE_LOCATION=${STORAGE_LOCATION}
      - OLLAMA_SERVICE_URL=${OLLAMA_BASE_PATH}
      - LLM_SERVICE_URL=${LLM_SERVICE_URL}
      - LLM_PROVIDER=${LLM_PROVIDER}
    env_file:
      - .env
    networks:
      - panic
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3001"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s