name: Hyperion Archive

services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - type: volume
        source: ollama_vol
        target: /root/.ollama
        volume:
          nocopy: true
    ports:
      - '127.0.0.1:11434:11434'
    networks:
      - panic
    restart: no
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-I",
          "http://localhost:11434 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
        reservations:
          memory: ${MEMORY_RESERVATION}
    security_opt:
      - no-new-privileges:true

  archive:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingLLM
    depends_on:
      ollama:
        condition: service_started
    volumes:
      - type: bind
        source: ${STORAGE_LOCATION}
        target: /app/server/storage
      - type: bind
        source: ${STORAGE_LOCATION}/.env
        target: /app/server/.env
      - type: bind
        source: ./collector/hotdir/
        target: /app/collector/hotdir
      - type: bind
        source: ./collector/outputs/
        target: /app/collector/outputs
    environment:
      - STORAGE_DIR=${STORAGE_DIR}
      - STORAGE_LOCATION=${STORAGE_LOCATION}
      - OLLAMA_SERVICE_URL=${OLLAMA_BASE_PATH}
      - LLM_SERVICE_URL=${LLM_SERVICE_URL}
      - LLM_PROVIDER=${LLM_PROVIDER}
    env_file:
      - .env
    ports:
      - '127.0.0.1:3001:3001'
    networks:
      - panic
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3001"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    # kics-scan ignore-block
    cap_add:
      - SYS_ADMIN
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

networks:
  panic:
    driver: bridge

volumes:
  ollama_vol:
    driver: local
  anythingllm_vol:
    driver: local